# Generated by Django 5.1.4 on 2025-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productimage_image_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizevariant',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='sizevariant',
            unique_together={('size_name',)},
        ),
    ]
