# Generated by Django 5.1.4 on 2025-12-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_sizevariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
